<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backtrace_data.proto

namespace GPBMetadata;

class BacktraceData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¥
backtrace_data.protocodectrl.data.backtrace_data"g
BacktraceData
name (	
filePath (	

lineNumber (
columnNumber (
code (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

