<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto

namespace GPBMetadata;

class Log
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BacktraceData::initOnce();
        $pool->internalAddGeneratedFile(
            '
ë
	log.protocodectrl.data.log"Â
Log
uuid (	:
stack (2+.codectrl.data.backtrace_data.BacktraceData

lineNumber (<
codeSnippet (2\'.codectrl.data.log.Log.CodeSnippetEntry
message (	
messageType (	
fileName (	
address (	
language	 (	
warnings
 (	2
CodeSnippetEntry
key (
value (	:8bproto3'
        , true);

        static::$is_initialized = true;
    }
}

