<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cc_service.proto

namespace Codectrl\Logs_service;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Returned by the procedures to describe the result of a request.
 *
 * Generated from protobuf message <code>codectrl.logs_service.RequestResult</code>
 */
class RequestResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string message = 1;</code>
     */
    protected $message = '';
    /**
     * Generated from protobuf field <code>.codectrl.logs_service.RequestStatus status = 2;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>optional .codectrl.auth_service.GenerateTokenRequestResult authStatus = 3;</code>
     */
    protected $authStatus = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $message
     *     @type int $status
     *     @type \Codectrl\Auth_service\GenerateTokenRequestResult $authStatus
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CcService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string message = 1;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.codectrl.logs_service.RequestStatus status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.codectrl.logs_service.RequestStatus status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Codectrl\Logs_service\RequestStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .codectrl.auth_service.GenerateTokenRequestResult authStatus = 3;</code>
     * @return \Codectrl\Auth_service\GenerateTokenRequestResult|null
     */
    public function getAuthStatus()
    {
        return $this->authStatus;
    }

    public function hasAuthStatus()
    {
        return isset($this->authStatus);
    }

    public function clearAuthStatus()
    {
        unset($this->authStatus);
    }

    /**
     * Generated from protobuf field <code>optional .codectrl.auth_service.GenerateTokenRequestResult authStatus = 3;</code>
     * @param \Codectrl\Auth_service\GenerateTokenRequestResult $var
     * @return $this
     */
    public function setAuthStatus($var)
    {
        GPBUtil::checkMessage($var, \Codectrl\Auth_service\GenerateTokenRequestResult::class);
        $this->authStatus = $var;

        return $this;
    }

}

