<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cc_service.proto

namespace Codectrl\Logs_service;

use UnexpectedValueException;

/**
 * Status codes for whether or not a particular request has succeeded.
 *
 * Protobuf type <code>codectrl.logs_service.RequestStatus</code>
 */
class RequestStatus
{
    /**
     * Generated from protobuf enum <code>CONFIRMED = 0;</code>
     */
    const CONFIRMED = 0;
    /**
     * Generated from protobuf enum <code>ERROR = 1;</code>
     */
    const ERROR = 1;

    private static $valueToName = [
        self::CONFIRMED => 'CONFIRMED',
        self::ERROR => 'ERROR',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

