<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cc_service.proto

namespace Codectrl\Logs_service;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Server details about the current gRPC server.
 *
 * Generated from protobuf message <code>codectrl.logs_service.ServerDetails</code>
 */
class ServerDetails extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string host = 1;</code>
     */
    protected $host = '';
    /**
     * Generated from protobuf field <code>uint32 port = 2;</code>
     */
    protected $port = 0;
    /**
     * Generated from protobuf field <code>uint64 uptime = 3;</code>
     */
    protected $uptime = 0;
    /**
     * Generated from protobuf field <code>bool requiresAuthentication = 4;</code>
     */
    protected $requiresAuthentication = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $host
     *     @type int $port
     *     @type int|string $uptime
     *     @type bool $requiresAuthentication
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CcService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string host = 1;</code>
     * @return string
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * Generated from protobuf field <code>string host = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->host = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 port = 2;</code>
     * @return int
     */
    public function getPort()
    {
        return $this->port;
    }

    /**
     * Generated from protobuf field <code>uint32 port = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPort($var)
    {
        GPBUtil::checkUint32($var);
        $this->port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 uptime = 3;</code>
     * @return int|string
     */
    public function getUptime()
    {
        return $this->uptime;
    }

    /**
     * Generated from protobuf field <code>uint64 uptime = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUptime($var)
    {
        GPBUtil::checkUint64($var);
        $this->uptime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool requiresAuthentication = 4;</code>
     * @return bool
     */
    public function getRequiresAuthentication()
    {
        return $this->requiresAuthentication;
    }

    /**
     * Generated from protobuf field <code>bool requiresAuthentication = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setRequiresAuthentication($var)
    {
        GPBUtil::checkBool($var);
        $this->requiresAuthentication = $var;

        return $this;
    }

}

